server:
  port: 8080
  host: 127.0.0.1

openapi:
  version: 0.1.0
  title: QuadroFlow API
  description: A visual organization application that combines the simplicity of the Kanban board with the fluidity of an agile workflow.

security:
  passwordCost: 12
  accessValidity: 900
  refreshValidity: 604800
