name: quadroflow
description: A visual organization application that combines the simplicity of the Kanban board with the fluidity of an agile workflow.

publish_to: "none"
homepage: https://softyes.com.br
repository: https://github.com/QuadroFlow/quadroflow_server

version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  path: ^1.9.1
  vaden: ^0.1.1
  dotenv: ^4.2.0

dev_dependencies:
  test: ^1.26.3
  build_runner: ^2.4.14
  very_good_analysis: ^9.0.0
  vaden_class_scanner: ^0.1.2
